version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: link-shortener_postgres-dev
    hostname: postgres
    volumes:
      - postgresData:/var/lib/postgresql/data/pgdata
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "UTC"
      PGTZ: "UTC"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgresData:
    name: postgresData
